## Create a 2x4 two dimensional matrix with random floats in it and in the next step determine the biggest element. 

# Approach 1

In [57]:
M = rand(2,4)

2×4 Array{Float64,2}:
 0.491981  0.274906  0.488363  0.991687
 0.688321  0.81607   0.846373  0.629282

In [58]:
N = zeros(8)

8-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [59]:
for i in [1:8]
    N[i] = M[i]
end

In [60]:
sort(N)[end]

0.9916867863863321

# Approach 2

In [51]:
M = rand(2,4)

2×4 Array{Float64,2}:
 0.18314   0.927125  0.0216314  0.550899
 0.752989  0.750147  0.516219   0.446911

In [53]:
n = vec(M)

8-element Array{Float64,1}:
 0.18314  
 0.752989 
 0.927125 
 0.750147 
 0.0216314
 0.516219 
 0.550899 
 0.446911 

In [54]:
sort(n)[end]

0.9271245290071801