In [76]:
# Numpy Tests

In [77]:
import numpy as np
print (np.__version__)

1.14.0


In [78]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [80]:
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [81]:
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [82]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack([a, b])


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [83]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)


array([2, 4])

In [84]:
np.where(a == b)

(array([1, 3, 5, 7]),)

In [85]:
a = np.array([2,6,1,9,10,3,27])
a_sol = a[(5<=a) & (a<=10)]
a_sol

array([ 6,  9, 10])

In [86]:
def maxx(x,y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
    
maxx(1,5)

5

In [87]:
def pair_max(x,y):
    """Get maximum of each pair in two arrays """
    if len(x) != len(y):
        return false
    z = np.array([0]*len(x))
    for i in range(int(len(x))):
        # print(x[i], y[i], maxx(x[i], y[i]))
        z[i] = (maxx(x[i],y[i]))
    return z
        

In [88]:
a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])
c = pair_max(a,b)
c

array([6, 7, 9, 8, 9, 7, 5])

In [94]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [97]:
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

/home/jens/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  """Entry point for launching an IPython kernel.


In [99]:
print(iris_1d.shape)

(150,)


In [100]:
species = np.array([row[4] for row in iris_1d])
species[:10]

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa'], dtype='|S18')